version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    links:
      - php-fpm
    volumes:
      - /var/www/html/:/var/www/html/
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    image: php:7.0-fpm
    expose:
      - "9000"
    volumes:
      - /var/www/html/:/var/www/html/
